name: .NET Restore from Codebelt
description: An opinionated action that restore the dependencies for specified projects or the solution itself.
inputs:
  projects:
    description: Optional path to the project(s) file to restore. Pass empty to restore all dependencies of a solution. Supports globbing. Default is an empty string.
    required: true
    default: ''
  verbosity-level:
    description: Sets the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]. The default is quiet.
    required: true
    default: 'quiet'
outputs:
  restoreCacheKey:
    description: The restore cache key that can be used by other actions.
    value: ${{ steps.generate-restore-cache-key.outputs.key }}
runs:
  using: composite
  steps:
    - name: Restore
      run: |
        if [ "${{ inputs.projects }}" == "" ]; then
            dotnet restore --verbosity ${{ inputs.verbosity-level }}
        else
            shopt -s globstar extglob
            for file in ${{ inputs.projects }}; do
              dotnet restore $file --verbosity ${{ inputs.verbosity-level }}
              echo "Restored '$file'"
            done
        fi
      shell: bash
branding:
  icon: 'umbrella'
  color: 'blue'
